# optional
props:
  version: v1  # project version
  appId: xxx-appId  # mas appid
  monitorId: xxx-monitor-id  # mas monitor id
  databaseName: xxx-database

# optional
etcd:
  address: ${etcd_address}
  apiVersion: v3  #etcd version
  username: ${etcd_username}
  password: ${etcd_password}
  httpsEnable: false

# require
datasource:
  ds0:
    url: tcp(127.0.0.1:3306)/ds0
    username: root
    password: root

# require
router:
  active: c0
  routeAlgorithm: single-read-write
  retry:
    times: 10
    delay: 50  # ms
  nodes:
    c0:
      master: ds0
      loadBalance: RANDOM
